# This file was generated by GoReleaser. DO NOT EDIT.
cask "trello-cli" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "903bf8189f9a72a0f8a6591e854823fde9a7625bc6c80b5a0a2ecae8b5bd4085"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d62547db170a9bfd9648bb6b0e39966b3aee61ce6749901aff5f22863a7e843"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3211009cbb0379618142eec451b7cd33d32a91c88c8405eb9035d6d494211726"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5b3e14e6104d0f112af793bb728133c9cf8cf1798c9f3c4ecf225952cf01ecf"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "trello-cli"
  desc "Manage Trello from the command line, or from an AI agent shelling out to it"
  homepage "https://github.com/abigotado/trello-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trello-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trello-cli"]
    end
  end

  # No zap stanza required

end
