# This file was generated by GoReleaser. DO NOT EDIT.
cask "trello-cli" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "a2b0c102652e7d80eb714730547f22559b28b1a322b2e5b4fbc2c37a2ee0b8dd"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0da395f6acc9881157c4f6e10ec65f0122a4423656719b13bd076620b26b61a"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "031109f06d42ad32b331906c8a6663c134c62d326af6885bc14ebcc3faae07a3"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "170a6592bfe96c89419edf4d4b52e7e42cc5879c9d2973c4aa9c4e853757e9e4"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "trello-cli"
  desc "Manage Trello from the command line, or from an AI agent shelling out to it"
  homepage "https://github.com/abigotado/trello-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trello-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trello-cli"]
    end
  end

  # No zap stanza required

end
