# This file was generated by GoReleaser. DO NOT EDIT.
cask "trello-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "32ff421a92d2fb464086a2b70572384dafdbb7652d6d21bc7d85ce7f5e973e11"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85008a0670e3b3586f2da132bb79d8a161ee70fcceaf45513aac341416deab19"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92663289706df39fe87ec1854eefbf84c9e10cc8c5e36b5477fcac772de45c7c"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1cf0d65f406b26594d924a718ca68575e72ccb9330cf702ae2427f89305687ea"
      url "https://github.com/abigotado/trello-cli/releases/download/v#{version}/trello-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "trello-cli"
  desc "Manage Trello from the command line, or from an AI agent shelling out to it"
  homepage "https://github.com/abigotado/trello-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trello-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trello-cli"]
    end
  end

  # No zap stanza required

end
